p3_dbt:
  outputs:
    dev:
      type: bigquery
      project: projet-3-wild
      dataset: raw_data
      threads: 4
      timeout_seconds: 300
      location: europe-west9
      method: service-account
      keyfile: /opt/airflow/cle_bigquery.json
  target: dev
